#ifndef BOARD_PROFILE_H
#define BOARD_PROFILE_H

// Compile-time board selection. The CYD profile remains the default so the
// existing Arduino IDE / default PlatformIO build behaves exactly as before.
#define BOARD_PROFILE_CYD 1
#define BOARD_PROFILE_HOSYOND40 2

#define BOARD_TOUCH_DRIVER_BITBANG 1
#define BOARD_TOUCH_DRIVER_TFT_ESPI 2

#ifndef BOARD_PROFILE
#define BOARD_PROFILE BOARD_PROFILE_CYD
#endif

#if BOARD_PROFILE == BOARD_PROFILE_HOSYOND40

#define BOARD_PROFILE_NAME "Hosyond 4.0 ST7796S"
#define BOARD_DISPLAY_WIDTH 480
#define BOARD_DISPLAY_HEIGHT 320
#define BOARD_TFT_ROTATION_NORMAL 1
#define BOARD_TFT_ROTATION_FLIPPED 3
#define BOARD_BACKLIGHT_PIN 27
#define BOARD_TOUCH_MOSI 13
#define BOARD_TOUCH_MISO 12
#define BOARD_TOUCH_CLK 14
#define BOARD_TOUCH_CS 33
#define BOARD_TOUCH_DRIVER BOARD_TOUCH_DRIVER_TFT_ESPI
#define BOARD_HAS_LDR_AUTOBRIGHTNESS 0
#define BOARD_USE_QUAD_SPRITE 0

#elif BOARD_PROFILE == BOARD_PROFILE_CYD

#define BOARD_PROFILE_NAME "CYD 2.8 ILI9341"
#define BOARD_DISPLAY_WIDTH 320
#define BOARD_DISPLAY_HEIGHT 240
#define BOARD_TFT_ROTATION_NORMAL 1
#define BOARD_TFT_ROTATION_FLIPPED 3
#define BOARD_BACKLIGHT_PIN 21
#define BOARD_TOUCH_MOSI 32
#define BOARD_TOUCH_MISO 39
#define BOARD_TOUCH_CLK 25
#define BOARD_TOUCH_CS 33
#define BOARD_TOUCH_DRIVER BOARD_TOUCH_DRIVER_BITBANG
#define BOARD_HAS_LDR_AUTOBRIGHTNESS 1
#define BOARD_USE_QUAD_SPRITE 1

#else
#error "Unknown BOARD_PROFILE"
#endif

#define BOARD_TOUCH_WIDTH BOARD_DISPLAY_WIDTH
#define BOARD_TOUCH_HEIGHT BOARD_DISPLAY_HEIGHT

#endif // BOARD_PROFILE_H
