#!/usr/bin/env python3
"""Generate fontTimeDigits.h: a digits-only anti-aliased VLW font for the
quad face's HH:MM display, embedded as a PROGMEM array for TFT_eSPI's
smooth-font renderer (loadFont / SMOOTH_FONT).

Rasterized from Liberation Sans Bold (SIL Open Font License 1.1,
https://github.com/liberationfonts/liberation-fonts) - its digits are
tabular (all the same advance), so the centered time doesn't jitter as the
minutes tick over. Only "0123456789:" is included to keep the flash cost
around 12KB.

Usage:  python3 tools/make_time_font.py   (writes ../fontTimeDigits.h)
Needs:  pip install pillow, and the Liberation fonts installed
        (Debian/Ubuntu: fonts-liberation).

VLW format (what TFT_eSPI's loadMetrics reads, all int32 big-endian):
  header: glyph count, version (11), point size, 0, ascent, descent
  per glyph: unicode, height, width, xAdvance, dY (baseline to bitmap top),
             dX, 0 - followed by all bitmaps (8-bit alpha, row-major)
The header ascent is written as the tallest glyph's dY (the digit cap
height): TFT_eSPI plots glyphs at cursorY + ascent - dY, so with TC_DATUM
the digit tops then land exactly on the y passed to drawString.
"""

import struct
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

FONT_PATH = "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf"
SIZE = 52  # "88:88" is 133px wide - fits a 160px quadrant like Font 4 x2 did
CHARS = "0123456789:"
OUT = Path(__file__).resolve().parent.parent / "fontTimeDigits.h"
ARRAY_NAME = "TIME_DIGITS_VLW"

font = ImageFont.truetype(FONT_PATH, SIZE)
ascent, descent = font.getmetrics()

glyphs = []
for ch in CHARS:
    x0, y0, x1, y1 = font.getbbox(ch)
    w, h = x1 - x0, y1 - y0
    img = Image.new("L", (w, h), 0)
    ImageDraw.Draw(img).text((-x0, -y0), ch, font=font, fill=255)
    glyphs.append({
        "code": ord(ch),
        "width": w,
        "height": h,
        "xadvance": round(font.getlength(ch)),
        "dy": ascent - y0,  # baseline to bitmap top
        "dx": x0,
        "bitmap": img.tobytes(),
    })

cap_ascent = max(g["dy"] for g in glyphs)
max_descent = max(g["height"] - g["dy"] for g in glyphs)

blob = struct.pack(">6i", len(glyphs), 11, SIZE, 0, cap_ascent, max_descent)
for g in glyphs:
    blob += struct.pack(">7i", g["code"], g["height"], g["width"],
                        g["xadvance"], g["dy"], g["dx"], 0)
for g in glyphs:
    blob += g["bitmap"]

lines = [
    "// Auto-generated by tools/make_time_font.py - do not edit by hand.",
    "//",
    f"// Anti-aliased VLW font, {SIZE}pt Liberation Sans Bold subset "
    f"(\"{CHARS}\"),",
    "// for the quad face's time digits (TFT_eSPI loadFont / SMOOTH_FONT).",
    "// Liberation Sans is (c) Red Hat / Google, SIL Open Font License 1.1:",
    "// https://github.com/liberationfonts/liberation-fonts",
    "//",
    f"// Digit cap height {cap_ascent}px, \"88:88\" width "
    f"{round(font.getlength('88:88'))}px, {len(blob)} bytes.",
    "",
    "#ifndef FONT_TIME_DIGITS_H",
    "#define FONT_TIME_DIGITS_H",
    "",
    "#include <pgmspace.h>",
    "",
    f"const uint8_t {ARRAY_NAME}[{len(blob)}] PROGMEM = {{",
]
for i in range(0, len(blob), 16):
    chunk = ", ".join(f"0x{b:02X}" for b in blob[i:i + 16])
    lines.append(f"    {chunk},")
lines += ["};", "", "#endif // FONT_TIME_DIGITS_H", ""]

OUT.write_text("\n".join(lines))
print(f"wrote {OUT} ({len(blob)} bytes, {len(glyphs)} glyphs, "
      f"ascent {cap_ascent}, descent {max_descent})")
